import 'package:technolenz/exports.dart';

class PortfolioConstants {
  static List<PortfolioItem> portfolioItems = [
    PortfolioItem(
      id: 'unit-converter',
      title: "Unit Converter",
      shortDescription: "Versatile unit converter for multiple categories",
      longDescription:
          "A comprehensive unit converter application built with Flutter that handles conversions across various measurement systems including length, weight, volume, temperature, and more. Features a clean interface with quick-copy functionality and conversion history.",
      imageUrls: const ["assets/images/fappproj/unitconverter-icon-512.png"],
      liveDemoUrl: "https://freelenz-unit-converter.web.app/welcome.html",
      githubUrl: "https://github.com/technolenz/unit-converter",
      category: PortfolioCategory.mobileApp,
      useCases: const [UseCase.finance, UseCase.utilities],
      techStack: const [TechStack.flutter, TechStack.provider, TechStack.dart],
      releaseDate: DateTime(2025, 1, 15),
      developmentTime: const Duration(days: 14),
      features: const [
        "20+ conversion categories",
        "Dark/light mode support",
        "Conversion history tracking",
        "live currency conversion",
      ],
      challenges: const [
        "Handling complex unit relationships",
        "Maintaining precision in conversions",
      ],
      learnings: const [
        "State management with Provider",
        "Internationalization techniques",
        "String mapping",
      ],
      downloadCount: 15,
      appRating: 3.8,
      vulnerabilitiesFound: const [],
    ),
    PortfolioItem(
      id: 'wordpair-app',
      title: "WordPair App",
      shortDescription: "Creative word pair generator",
      longDescription:
          "An application that generates interesting word combinations to spark creativity. Users can save their favorite pairs, share them, and explore linguistic patterns. Built with a focus on minimalistic design principles.",
      imageUrls: const ["assets/images/fappproj/wordpairapp_icon-512.png"],
      liveDemoUrl: "https://word-pair-app.web.app/welcome.html",
      githubUrl: "https://github.com/technolenz/wordpair-app",
      category: PortfolioCategory.mobileApp,
      useCases: const [UseCase.productivity, UseCase.education],
      techStack: const [TechStack.flutter, TechStack.provider, TechStack.dart],
      releaseDate: DateTime(2024, 12, 23),
      developmentTime: const Duration(days: 7),
      features: const [
        "Thousands of word combinations",
        "Favorite saving functionality",
        "Recycling Bin",
      ],
      challenges: const ["Generating meaningful pairs", "Maintaining app performance"],
      learnings: const ["Basic state management", "UI design principles"],
      downloadCount: 1200,
      appRating: 4.2,
      vulnerabilitiesFound: const [],
    ),
    PortfolioItem(
      id: 'qr4all',
      title: "QR4ALL",
      shortDescription: "QR code scanner and generator",
      longDescription:
          "A comprehensive QR code solution that allows users to both scan existing codes and generate new ones for various purposes including URLs, contact information, WiFi credentials, and custom messages. Features history tracking and bulk operations.",
      imageUrls: const [
        "assets/images/fappproj/qr4all_512.png",
        "assets/images/qr4all/screen_1.png",
        "assets/images/qr4all/screen_2.png",
      ],
      liveDemoUrl: "https://qr4all.web.app/welcome.html",
      githubUrl: "https://github.com/technolenz/qr4all",
      category: PortfolioCategory.mobileApp,
      useCases: const [UseCase.utilities],
      techStack: const [TechStack.flutter],
      releaseDate: DateTime(2025, 1, 27),
      developmentTime: const Duration(days: 20),
      features: const ["Fast QR code scanning", "Multiple generation types", "Scan history"],
      challenges: const ["Camera performance optimization", "QR code generation algorithms"],
      learnings: const ["Camera API integration", "Image processing techniques"],
      downloadCount: 38,
      appRating: 4.7,
      vulnerabilitiesFound: const [],
    ),
    PortfolioItem(
      id: 'fileghost',
      title: "FileGhost",
      shortDescription: "Secure file-hiding application",
      longDescription:
          "A privacy-focused application that allows users to securely hide sensitive files behind a PIN-protected interface. Implements local encryption and decryption without cloud storage for maximum security. Features a beautiful dark-themed UI.",
      imageUrls: const [
        "assets/images/fappproj/fileghost.png",
        "assets/images/fappproj/fileghost/fileman.png",
        "assets/images/fappproj/fileghost/lock.png",
        "assets/images/fappproj/fileghost/settings.png",
        "assets/images/fappproj/fileghost/splash.png",
      ],
      liveDemoUrl: "https://fileghost.web.app",
      githubUrl: "https://github.com/technolenz/fileghost",
      category: PortfolioCategory.mobileApp,
      useCases: const [UseCase.utilities, UseCase.utilities],
      techStack: const [TechStack.flutter],
      releaseDate: DateTime(2025, 3, 5),
      developmentTime: const Duration(days: 14),
      features: const [
        "PIN-protected access",
        "Local file encryption",
        "Biometrics Authentication",
      ],
      challenges: const ["File system operations", "Maintaining performance with large files"],
      learnings: const ["Local storage management", "Basic security principles"],
      downloadCount: 42,
      appRating: 3.9,
      vulnerabilitiesFound: const [],
    ),
    PortfolioItem(
      id: 'wisp-ai',
      title: "Wisp AI",
      shortDescription: "Gesture-controlled AI chatbot",
      longDescription:
          "An innovative chat application that combines Gemini AI with gesture controls for a unique user experience. Users can interact through both text and hand gestures captured via device camera. Features real-time responses and conversation history.",
      imageUrls: const ["assets/images/fappproj/wisp.png"],
      liveDemoUrl: "https://wisp.web.app/welcome.html",
      githubUrl: "https://github.com/technolenz/wisp-ai",
      category: PortfolioCategory.mobileApp,
      useCases: const [UseCase.productivity, UseCase.techDemo],
      techStack: const [TechStack.flutter, TechStack.provider, TechStack.firebase],
      releaseDate: DateTime(2025, 2, 12),
      developmentTime: const Duration(days: 12),
      features: const [
        "Gesture recognition",
        "Real-time AI responses",
        "Conversation history sync",
      ],
      challenges: const ["Gesture detection accuracy", "AI response optimization"],
      learnings: const ["Firebase integration", "Machine learning basics"],
      downloadCount: 31,
      appRating: 2.8,
      vulnerabilitiesFound: const [],
    ),
    PortfolioItem(
      id: 'md-lenz',
      title: "MD-Lenz",
      shortDescription: "Markdown editor with cloud sync",
      longDescription:
          "A feature-rich Markdown editor that supports real-time preview, syntax highlighting, and cloud synchronization. Designed for developers and writers who need a distraction-free environment with powerful formatting options and cross-device access.",
      imageUrls: const [
        "assets/images/fappproj/mdlenz.png",
        "assets/images/fappproj/mdlenz/editor.png",
        "assets/images/fappproj/mdlenz/editor2.png",
        "assets/images/fappproj/mdlenz/filemanager.png",
        "assets/images/fappproj/mdlenz/home.png",
        "assets/images/fappproj/mdlenz/home2.png",
        "assets/images/fappproj/mdlenz/settings.png",
        "assets/images/fappproj/mdlenz/settings2.png",
      ],
      liveDemoUrl: "https://mdlenz.web.app",
      githubUrl: "https://github.com/technolenz/mdlenz",
      category: PortfolioCategory.mobileApp,
      useCases: const [UseCase.productivity],
      techStack: const [TechStack.flutter, TechStack.firebase, TechStack.provider],
      releaseDate: DateTime(2025, 2, 8),
      developmentTime: const Duration(days: 30),
      features: const ["Real-time Markdown preview", "Cloud synchronization", "Local Exports"],
      challenges: const ["Markdown parsing performance", "Conflict resolution in sync"],
      learnings: const ["Firebase authentication", "Complex state management"],
      downloadCount: 120,
      appRating: 4.4,
      vulnerabilitiesFound: const [],
    ),
  ];
}
